CREATE TABLE CONTACTS (
    ID VARCHAR(36) NOT NULL UNIQUE,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    TITLE VARCHAR(255),
    PHONE VARCHAR(255),
    ADDRESS VARCHAR(255),
    STATUS VARCHAR(255),
    PHOTO_URL VARCHAR(255),
    PRIMARY KEY (ID)
);
